import json
from orchestrator.state import CaseState, FinancialPlan, SchemeTier, ApplicationStatus, SessionMeta
from module2_financial import policy_scheme_agent
from module2_financial import application_tracker

def main():
    print("=== Testing Policy RAG Agent ===")
    # 1. Setup mock state with a Financial Plan routed to 'micro_finance'
    state = CaseState(
        session_meta=SessionMeta(session_id="test-123"),
        financial_plan=FinancialPlan(
            scheme_tier=SchemeTier(
                name="micro_finance",
                display_name="Micro Finance Scheme",
                max_project_cost=140000.0,
                max_loan_amount=125000.0,
                interest_rate=0.065,
                tenure_years=3,
                moratorium_months=3
            ),
            maximum_loan_eligibility=125000.0
        )
    )
    
    # Run the RAG Agent
    policy_scheme_agent.run(state)
    print("\nPolicy Explanation Generated by Agent:")
    print("-" * 50)
    print(state.financial_plan.policy_explanation)
    print("-" * 50)


    print("\n=== Testing Application Tracker ===")
    # 2. Setup mock Application Status with missing documents
    state.application_status = ApplicationStatus()
    state.application_status.checklist = {
        "identity_proof": "complete",
        "address_proof": "complete",
        "quotation_machinery": "missing" # Missing document!
    }
    
    print("\nRun 1: Documents Missing")
    application_tracker.run(state)
    print(f"Status: {state.application_status.disbursement_status}")
    
    print("\nRun 2: Documents Complete")
    state.application_status.checklist["quotation_machinery"] = "complete"
    application_tracker.run(state)
    print(f"Status: {state.application_status.disbursement_status}")
    
    print("\nRun 3: Simulate 'Under Verification' -> 'Sanctioned'")
    application_tracker.run(state)
    print(f"Status: {state.application_status.disbursement_status}")
    print(f"Sanctioned Amount: {state.application_status.sanctioned_amount}")

    print("\nRun 4: Simulate 'Sanctioned' -> 'Disbursed'")
    application_tracker.run(state)
    print(f"Status: {state.application_status.disbursement_status}")
    print(f"Disbursement Date: {state.application_status.disbursement_date}")

if __name__ == "__main__":
    main()
