/**
 * Hindi for the free-text fields of data/reference/business_catalog.json (key inputs, buyers, licences, price units),
 * so catalog-derived items render in the app language. Unknown text falls back to the English source.
 */
import type { Bi } from "../i18n";

const HI: Record<string, string> = {
  "Animal insurance": "पशु बीमा",
  "Artisan card (optional)": "कारीगर कार्ड (वैकल्पिक)",
  "Average basket value, INR": "औसत खरीद मूल्य",
  "Average ticket value, INR": "औसत बिक्री मूल्य",
  "Ayurvedic producers": "आयुर्वेदिक उत्पादक",
  "Bakeries": "बेकरी",
  "Bee boxes": "मधुमक्खी बक्से",
  "Bee colonies": "मधुमक्खी कॉलोनी",
  "Breeding stock": "नस्ल के पशु",
  "Bridal bookings": "दुल्हन की बुकिंग",
  "Browse and fodder": "चारा और पत्तियाँ",
  "Carpet exporters": "कालीन निर्यातक",
  "Cattle feed concentrate": "पशु आहार (दाना)",
  "Chicks": "चूज़े",
  "Commuters": "आने-जाने वाले यात्री",
  "Cosmetics and consumables": "सौंदर्य सामग्री",
  "Dairy cooperative collection centre": "डेयरी सहकारी संग्रह केंद्र",
  "Direct village customers": "गाँव के सीधे ग्राहक",
  "Dyeing job-work": "रंगाई का जॉब-वर्क",
  "Dyes": "रंग",
  "Edible oil": "खाने का तेल",
  "Egg trays": "अंडे की ट्रे",
  "Egg wholesalers": "अंडा थोक विक्रेता",
  "Electricity": "बिजली",
  "Electricity load sanction": "बिजली लोड मंज़ूरी",
  "FMCG stock from distributors": "वितरकों से रोज़मर्रा का सामान",
  "FSSAI basic registration": "FSSAI बेसिक पंजीकरण",
  "FSSAI basic registration (if selling processed milk products)": "FSSAI बेसिक पंजीकरण (दूध से बने उत्पाद बेचने पर)",
  "FSSAI state licence / registration": "FSSAI राज्य लाइसेंस / पंजीकरण",
  "Fabric (customer-supplied or bought)": "कपड़ा (ग्राहक का या खरीदा हुआ)",
  "Fertiliser dealer authorisation": "खाद डीलर अनुमति",
  "Fingerlings": "मछली के बच्चे",
  "Fish feed": "मछली आहार",
  "Fish mandi commission agents": "मछली मंडी के आढ़ती",
  "Green and dry fodder": "हरा और सूखा चारा",
  "Handloom cooperatives": "हथकरघा सहकारी समितियाँ",
  "Honey extractor": "शहद निकालने की मशीन",
  "Honey processors": "शहद प्रोसेसर",
  "Households": "घरेलू ग्राहक",
  "Households (custom milling)": "घरेलू ग्राहक (पिसाई)",
  "Households within walking distance": "पैदल दूरी के घर",
  "INR per animal (live weight basis)": "प्रति पशु (जीवित वज़न के आधार पर)",
  "INR per cup / plate": "प्रति कप / प्लेट",
  "INR per kg": "प्रति किलो",
  "INR per litre of milk": "प्रति लीटर दूध",
  "INR per piece": "प्रति पीस",
  "INR per quintal of mustard seed (input benchmark)": "प्रति क्विंटल सरसों (कच्चे माल का भाव)",
  "INR per quintal of wheat (input benchmark)": "प्रति क्विंटल गेहूँ (कच्चे माल का भाव)",
  "INR per repair job": "प्रति मरम्मत",
  "INR per service": "प्रति सेवा",
  "INR per square foot (job-work rate)": "प्रति वर्ग फुट (जॉब-वर्क दर)",
  "INR per stitched garment": "प्रति सिला कपड़ा",
  "INR per tray of 30 eggs": "प्रति 30 अंडों की ट्रे",
  "Insecticide sale licence": "कीटनाशक बिक्री लाइसेंस",
  "Kirana stores": "किराना दुकानें",
  "LPG": "एलपीजी गैस",
  "Layer feed": "लेयर मुर्गी आहार",
  "Livestock haat traders": "पशु हाट के व्यापारी",
  "Local body / panchayat NOC for poultry shed": "मुर्गी शेड के लिए पंचायत / निकाय अनापत्ति",
  "Local body vending permission": "निकाय से ठेला-दुकान अनुमति",
  "Local boutiques": "स्थानीय बुटीक",
  "Local fish vendors": "स्थानीय मछली विक्रेता",
  "Local meat shops": "स्थानीय मीट दुकानें",
  "Local retail": "स्थानीय खुदरा बिक्री",
  "Local retailers": "स्थानीय दुकानदार",
  "Local sweet shops": "स्थानीय मिठाई की दुकानें",
  "Loom spares": "करघे के पुर्ज़े",
  "Looms": "करघे",
  "Market visitors": "बाज़ार आने वाले लोग",
  "Master weavers": "मास्टर बुनकर",
  "Milch animals": "दुधारू पशु",
  "Milk": "दूध",
  "Mill stones / spares": "चक्की के पत्थर / पुर्ज़े",
  "Mobile users in the village cluster": "गाँव-क्षेत्र के मोबाइल उपयोगकर्ता",
  "Mustard seed": "सरसों",
  "Oil wholesalers": "तेल थोक विक्रेता",
  "Packaging": "पैकिंग सामग्री",
  "Parlour equipment": "पार्लर उपकरण",
  "Pond lease or ownership document": "तालाब का पट्टा या मालिकाना कागज़",
  "Pond lime and manure": "तालाब के लिए चूना और खाद",
  "Poultry feed": "मुर्गी आहार",
  "Pullets": "बड़ी मुर्गियाँ (पुलेट)",
  "Raw vegetables and spices": "कच्ची सब्ज़ियाँ और मसाले",
  "Repair toolkit": "मरम्मत के औज़ार",
  "Retail showrooms": "खुदरा शोरूम",
  "SHG federations": "स्वयं सहायता समूह महासंघ",
  "School uniform orders": "स्कूल वर्दी के ऑर्डर",
  "Seed and fertiliser stock from authorised distributors": "अधिकृत वितरकों से बीज और खाद",
  "Seed dealer licence": "बीज डीलर लाइसेंस",
  "Sewing machines": "सिलाई मशीनें",
  "Shop and establishment registration": "दुकान एवं प्रतिष्ठान पंजीकरण",
  "Snack ingredients": "नाश्ते का सामान",
  "Spare parts from district wholesalers": "ज़िले के थोक विक्रेताओं से पुर्ज़े",
  "Staples from wholesale mandi": "थोक मंडी से राशन",
  "Surrounding farmers": "आसपास के किसान",
  "Tea leaves": "चाय पत्ती",
  "Thread and accessories": "धागा और सामान",
  "Udyam registration": "उद्यम पंजीकरण",
  "Vaccines": "टीके",
  "Veterinary services": "पशु चिकित्सा सेवा",
  "Weaver identity card (Handloom Mark optional)": "बुनकर पहचान पत्र (हैंडलूम मार्क वैकल्पिक)",
  "Weekly haat": "साप्ताहिक हाट",
  "Wheat and other grains": "गेहूँ और दूसरे अनाज",
  "Women in the village cluster": "गाँव-क्षेत्र की महिलाएँ",
  "Wool and cotton yarn": "ऊनी और सूती धागा",
  "Yarn": "धागा",
};

/** Bilingual form of a catalog string (Hindi falls back to the English source when not listed). */
export function catalogBi(text: string): Bi {
  return { en: text, hi: HI[text] ?? text };
}

export const catalogHi = (text: string): string => HI[text] ?? text;
