// Builds src/i18n/strings/catalog.ts: translation keys for activity names, catalog free text and place names.
// English comes from the catalog / data pack; Hindi from the existing authored tables. Run: node scripts/build_catalog_strings.mjs
import fs from "fs";
import { fileURLToPath } from "url";

const root = fileURLToPath(new URL("..", import.meta.url));
const catalog = JSON.parse(fs.readFileSync(`${root}../data/reference/business_catalog.json`, "utf8"));
const districts = JSON.parse(fs.readFileSync(`${root}src/core/data/districts.json`, "utf8"));
const stateRef = JSON.parse(fs.readFileSync(`${root}src/core/data/state_reference.json`, "utf8"));
const hiCatalog = fs.readFileSync(`${root}src/core/catalogHi.ts`, "utf8");
const activitiesTs = fs.readFileSync(`${root}src/data/activities.ts`, "utf8");

export const slug = (t) => t.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
const HI = Object.fromEntries([...hiCatalog.matchAll(/^\s+"([^"]+)": "([^"]+)",$/gm)].map((m) => [m[1], m[2]]));
const DISPLAY_HI = Object.fromEntries([...activitiesTs.matchAll(/^\s+(\w+): \{ name: \{ en: "([^"]+)", hi: "([^"]+)" \}/gm)].map((m) => [m[1], [m[2], m[3]]]));
const EXTRA_ACT_HI = {
  poultry_layer: ["Poultry layer farm", "मुर्गी लेयर फार्म"],
  fisheries_pond: ["Fish farming (pond)", "तालाब में मछली पालन"],
  beekeeping: ["Beekeeping and honey", "मधुमक्खी पालन और शहद"],
  mustard_oil_mill: ["Mustard oil mini mill", "सरसों तेल मिनी मिल"],
  agri_input_depot: ["Seed & fertiliser shop", "बीज और खाद की दुकान"],
};

const en = {};
const hi = {};
for (const a of catalog.activities) {
  const [e, h] = DISPLAY_HI[a.id] ?? EXTRA_ACT_HI[a.id] ?? [a.category, a.category];
  en[`activity.${a.id}`] = e;
  hi[`activity.${a.id}`] = h;
  for (const text of [...a.key_inputs, ...a.buyers, ...a.licences, a.price_unit]) {
    en[`catalog.${slug(text)}`] = text;
    hi[`catalog.${slug(text)}`] = HI[text] ?? text;
  }
}
for (const d of districts) {
  en[`place.district.${d.id}`] = d.name.en;
  hi[`place.district.${d.id}`] = d.name.hi;
}
for (const [name, info] of Object.entries(stateRef.states)) {
  en[`place.state.${slug(name)}`] = name;
  hi[`place.state.${slug(name)}`] = (info.aliases ?? []).find((x) => /[ऀ-ॿ]/.test(x)) ?? name;
}

const body = (o) => Object.entries(o).map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n");
fs.writeFileSync(
  `${root}src/i18n/strings/catalog.ts`,
  `import type { Strings } from "../index";\n\n/** Generated by scripts/build_catalog_strings.mjs — activity names, catalog free text and place names. */\nconst strings: Strings = {\n  en: {\n${body(en)}\n  },\n  hi: {\n${body(hi)}\n  },\n};\n\nexport default strings;\n`,
);
console.log(`catalog strings: ${Object.keys(en).length} keys`);
